agent_name: drqv2
# task settings
frame_stack: 3
action_repeat: 2
discount: 0.99
# train settings
num_seed_frames: 4000
# replay buffer
replay_buffer_size: 1000000
nstep: 3
batch_size: 256
# agent
lr: 1e-4
feature_dim: 50

agent:
  _target_: drqv2.DrQV2Agent
  encoder:
    _target_: drqv2.Encoder
    obs_shape: ${agent.obs_shape}
  actor:
    _target_: drqv2.Actor
    encoder: ${agent.encoder}
    action_shape: ${agent.action_shape}
    feature_dim: ${agent.feature_dim}
    hidden_dim: ${agent.hidden_dim}
  critic:
    _target_: drqv2.Critic
    encoder: ${agent.encoder}
    action_shape: ${agent.action_shape}
    feature_dim: ${agent.feature_dim}
    hidden_dim: ${agent.hidden_dim}
  obs_shape: ???
  action_shape: ???
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.01
  update_every_steps: 2
  use_tb: ${use_tb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3
  encoder_lr: ${lr}
  actor_lr: ${lr}
  critic_lr: ${lr}
